import type { ArenaGame, GlobalEventId } from './types';

export const ARENA_GAMES: { id: ArenaGame; name: string; icon: string; desc: string; seconds: number }[] = [
  { id: 'trivia', name: 'Trivia relámpago', icon: '🧠', desc: 'Tres preguntas para todos. Puntos por acertar y por velocidad.', seconds: 45 },
  { id: 'cana', name: 'Caña dulce', icon: '🍬', desc: 'Cinco segundos: tocá la pantalla la mayor cantidad de veces.', seconds: 8 },
  { id: 'barra', name: 'Frená la barra', icon: '🎯', desc: 'La aguja va y viene. Frenala lo más cerca del centro. Tres intentos.', seconds: 25 },
  { id: 'cuantos', name: '¿Cuántos hay?', icon: '🔢', desc: 'Una pregunta con número. El que más se acerca gana.', seconds: 20 },
  { id: 'bomba', name: 'Palabra bomba', icon: '💣', desc: 'Escribí una palabra que contenga la sílaba antes de que explote. Dos vidas.', seconds: 180 },
  { id: 'sapos', name: 'Carrera de sapos', icon: '🐸', desc: 'Los sapos saltan solos y cada vez más rápido; vos solo cambiás de carril. Charco = afuera. Primero en la meta gana.', seconds: 25 },
  { id: 'oeste', name: 'Duelo del Oeste', icon: '🤠', desc: 'Cuando suene la campana, tocá a quién disparar. El más rápido dispara primero.', seconds: 60 },
  { id: 'rayo', name: 'Esquivá el rayo', icon: '⚡', desc: 'Elegí dónde pararte. Caen rayos. El último en pie gana.', seconds: 60 },
  { id: 'penales', name: 'Penales', icon: '⚽', desc: 'Tres penales: frená la fuerza y la dirección. El arquero se tira a un lado.', seconds: 40 },
  { id: 'globos', name: 'Ruleta rusa de globos', icon: '🎈', desc: 'Un globo tiene la aguja. Por turnos, pinchá uno. El que la encuentra, afuera.', seconds: 90 },
  { id: 'dibujo', name: 'Adiviná el dibujo', icon: '🎨', desc: 'Uno dibuja, los demás adivinan. El primero que acierta gana; el dibujante también cobra.', seconds: 60 },
  { id: 'cartas', name: 'Cartas contra el Paraguay', icon: '🃏', desc: 'El juez lee una frase con hueco; los demás la completan con una de sus 6 cartas. El juez elige la más graciosa. 3 rondas.', seconds: 150 },
  { id: 'borrosa', name: 'La foto borrosa', icon: '🔍', desc: 'Una imagen se va destapando. El primero que toca la respuesta correcta gana la ronda; si errás, quedás afuera esa ronda. 3 rondas.', seconds: 45 },
  { id: 'cadena', name: 'Ordená la cadena', icon: '🔗', desc: 'Cuatro cosas para ordenar con un criterio. Tocalas en orden. Puntos por cada posición correcta. 2 rondas.', seconds: 50 },
  { id: 'ruleta', name: 'Ruleta de la muerte', icon: '🔫', desc: 'Un revólver con una bala pasa de mano en mano. Apretá, girá el tambor o pasá (una vez). El último en pie gana.', seconds: 90 },
  { id: 'bomba2', name: 'Plantá la bomba', icon: '🧨', desc: 'El que cayó en la Arena es el saboteador y elige el cable trampa; los demás cortan uno. Quien corta la trampa vuela. 3 rondas.', seconds: 75 },
];

export const ARENA_REWARDS = [300, 150, 50];

/** ¿Cuántos hay? — pregunta numérica y respuesta. */
export const CUANTOS: { q: string; a: number; unit?: string }[] = [
  { q: '¿Cuántos kilómetros hay de Asunción a Ciudad del Este por la Ruta PY02?', a: 327, unit: 'km' },
  { q: '¿Cuántos kilómetros hay de Asunción a Encarnación?', a: 370, unit: 'km' },
  { q: '¿Cuántos departamentos tiene Paraguay?', a: 17 },
  { q: '¿En qué año se fundó Asunción?', a: 1537 },
  { q: '¿En qué año terminó la Guerra del Chaco?', a: 1935 },
  { q: '¿Cuántos metros de altura tiene el Cerro Tres Kandú?', a: 842, unit: 'm' },
  { q: '¿Cuántos kilómetros de largo tiene la represa de Itaipú (su muro)?', a: 8, unit: 'km' },
  { q: '¿Cuántos megavatios de potencia instalada tiene Itaipú?', a: 14000, unit: 'MW' },
  { q: '¿Cuántos habitantes tiene Paraguay aproximadamente (en millones, redondeá)?', a: 7 },
  { q: '¿Cuántos senadores tiene el Congreso paraguayo?', a: 45 },
  { q: '¿Cuántos diputados tiene la Cámara?', a: 80 },
  { q: '¿En qué año se independizó Paraguay?', a: 1811 },
  { q: '¿En qué año cayó Stroessner?', a: 1989 },
  { q: '¿Cuántos metros de largo tiene el Puente de la Amistad?', a: 552, unit: 'm' },
  { q: '¿Cuántas cuerdas tiene el arpa paraguaya clásica?', a: 36 },
  { q: '¿A qué altura sobre el nivel del mar está Asunción, aproximadamente?', a: 43, unit: 'm' },
  { q: '¿Cuántos kilómetros cuadrados tiene Paraguay (redondeá en miles)?', a: 406752, unit: 'km²' },
  { q: '¿Cuántos kilómetros tiene el río Paraguay?', a: 2621, unit: 'km' },
  { q: '¿En qué año Olimpia ganó su primera Copa Libertadores?', a: 1979 },
  { q: '¿En qué año ganó Paraguay la medalla de plata olímpica en fútbol?', a: 2004 },
  { q: '¿Cuántos jugadores tiene un equipo de fútbol en cancha?', a: 11 },
  { q: '¿Cuántas casas tiene el banco en Ñandepoly?', a: 32 },
  { q: '¿Cuántas casillas tiene el tablero de Ñandepoly?', a: 44 },
  { q: '¿Cuántos guaraníes (en miles) cuesta el Palacio de López en el tablero?', a: 400 },
  { q: '¿Cuántos grados llegó la temperatura récord en Paraguay (aprox.)?', a: 45, unit: '°C' },
  { q: '¿En qué año se promulgó la Constitución vigente?', a: 1992 },
  { q: '¿Cuántos kilómetros hay de Asunción a Concepción?', a: 415, unit: 'km' },
  { q: '¿Cuántos kilómetros hay de Asunción a Pedro Juan Caballero?', a: 460, unit: 'km' },
  { q: '¿Cuántos kilómetros hay de Asunción a Caacupé?', a: 54, unit: 'km' },
  { q: '¿Cuántos kilómetros hay de Asunción a Villarrica?', a: 173, unit: 'km' },
  { q: '¿Cuántos kilómetros hay de Asunción a Filadelfia (Chaco)?', a: 470, unit: 'km' },
  { q: '¿Cuántos kilómetros hay de Asunción a Pilar?', a: 358, unit: 'km' },
  { q: '¿Cuántos minutos dura un partido de fútbol sin alargue?', a: 90 },
  { q: '¿Cuántos años duró la dictadura de Stroessner?', a: 35 },
  { q: '¿Cuántos hijos tuvieron Tau y Kerana en la mitología guaraní?', a: 7 },
  { q: '¿Cuántas estrellas tiene el escudo de la bandera paraguaya?', a: 1 },
  { q: '¿En qué año murió el Mariscal López?', a: 1870 },
  { q: '¿Cuántos kilómetros tiene la Costanera de Asunción (primera etapa)?', a: 3, unit: 'km' },
  { q: '¿Cuántos días tiene un año bisiesto?', a: 366 },
  { q: '¿Cuántos guaraníes (en miles) cobrás al pasar por Salida?', a: 200 },
];

/** Sílabas para la Palabra bomba, de más fáciles a más difíciles. */
export const BOMB_SYLLABLES = {
  facil: ['CA', 'MA', 'TA', 'RA', 'PA', 'LA', 'SA', 'NA', 'DA', 'TO', 'CO', 'MO', 'RO', 'LO', 'TE', 'RE', 'ME', 'SE', 'DE', 'LE', 'AR', 'ER', 'OR', 'EN', 'AN', 'ES', 'AS', 'ON', 'IN', 'AL', 'EL'],
  medio: ['TOM', 'CAR', 'MAR', 'PAR', 'TRA', 'PRE', 'CON', 'COM', 'POR', 'PER', 'TER', 'MEN', 'CAN', 'TAN', 'SAN', 'PLA', 'BRA', 'GRA', 'FRE', 'DOR', 'DAD', 'CIA', 'CIO', 'ENT', 'ANT', 'IST', 'AST', 'OST', 'UND', 'AMB'],
  dificil: ['ÑA', 'ÑO', 'GUA', 'QUI', 'ZO', 'JU', 'XI', 'YU', 'HUE', 'PSI', 'BLI', 'CRU', 'FLU', 'GNO', 'TRU', 'OBS', 'ABS', 'ADJ', 'INM', 'EXT'],
};

/** Palabras paraguayas y guaraníes que también valen en la Palabra bomba (sin acentos). */
export const PARAGUAYISMOS = [
  'terere', 'chipa', 'mbeju', 'sopa', 'vori', 'kivevé', 'kiveve', 'mbaipy', 'chipaguasu', 'mburucuya', 'nanduti', 'aopoi', 'guarania', 'polca',
  'pombero', 'kurupi', 'jasy', 'jatere', 'luison', 'moñai', 'monai', 'tejujagua', 'karai', 'kuñatai', 'kunatai', 'mita', 'jaha', 'aguyje', 'nande', 'ñande',
  'mbarakaja', 'jagua', 'kavaju', 'karumbe', 'mborevi', 'kapiyva', 'yvyra', 'kaaguy', 'oga', 'tape', 'jopara', 'guarani', 'mate', 'yerba',
  'chipero', 'chipera', 'cocido', 'clerico', 'mandioca', 'tembiu', 'asado', 'chaco', 'guasu', 'mbokaja', 'yvoty', 'mbarete', 'kaigue', 'pytu', 'pyta', 'hovy', 'moroti',
  'sayju', 'pirevai', 'ñembo', 'nembo', 'vyro', 'tavy', 'mbore', 'nderakore', 'ndera', 'chake', 'nde', 'che', 'ore', 'pee', 'hae', 'aipo', 'kore', 'purete', 'mbaeteko',
  'tereremo', 'chipazo', 'guaranies', 'asuncion', 'luque', 'encarnacion', 'caacupe', 'villarrica', 'pilar', 'concepcion', 'itaipu', 'yacyreta', 'tacumbu',
  'lambare', 'capiata', 'aregua', 'itaugua', 'ypacarai', 'paraguari', 'caaguazu', 'guaira', 'itapua', 'misiones', 'amambay', 'boqueron', 'chaqueño', 'chaqueno',
  'sapukai', 'purahei', 'galopera', 'chamame', 'kyre', 'yvaga', 'jopoi', 'tupa', 'tupasy', 'karaiguasu', 'mbaracaya', 'jaguarete', 'mburuvicha', 'tekove', 'tekoha',
];

/** Palabras para Adiviná el dibujo (objetos y cosas paraguayas). */
export const DRAW_WORDS = [
  'mate', 'terere', 'chipa', 'arpa', 'carreta', 'sopa paraguaya', 'bombilla', 'guampa', 'jaguarete', 'carpincho', 'tucan', 'ñandu', 'lapacho', 'cocotero',
  'puente', 'represa', 'colectivo', 'moto', 'estadio', 'pelota', 'bandera', 'escudo', 'palacio', 'catedral', 'rio', 'canoa', 'pescado', 'surubi', 'sandia', 'mandioca',
  'asado', 'parrilla', 'sombrero', 'poncho', 'guitarra', 'acordeon', 'globo', 'cohete', 'toro', 'vaca', 'caballo', 'gallo', 'pombero', 'luna', 'sol', 'tormenta',
  'arbol', 'flor', 'ñanduti', 'hamaca', 'casa', 'iglesia', 'cerro', 'aeropuerto', 'avion', 'tren', 'bicicleta', 'heladera', 'ventilador', 'termo', 'yerba',
];

export const EVENTS: { id: GlobalEventId; name: string; icon: string; desc: string; instant: boolean }[] = [
  { id: 'tranquilidad', name: 'Tranquilidad', icon: '😌', desc: 'Una vuelta normal. Disfrutá la calma.', instant: true },
  { id: 'hora_feliz', name: 'Hora feliz', icon: '🍻', desc: 'Todos los alquileres se cobran doble durante esta vuelta.', instant: false },
  { id: 'paro_ande', name: 'Paro de la ANDE', icon: '🔌', desc: 'Servicios y transportes no cobran alquiler esta vuelta.', instant: false },
  { id: 'aguinaldo', name: 'Aguinaldo', icon: '💰', desc: 'Todos cobran ₲ 100.000 del banco.', instant: true },
  { id: 'control_set', name: 'Control de la SET', icon: '🕵️', desc: 'El que más efectivo tiene paga el 10 % al banco.', instant: true },
  { id: 'boom', name: 'Boom inmobiliario', icon: '🏗️', desc: 'Casas y hoteles a mitad de precio durante esta vuelta.', instant: false },
  { id: 'inflacion', name: 'Inflación', icon: '📈', desc: 'Todos los alquileres suben 50 % durante esta vuelta.', instant: false },
  { id: 'dia_nino', name: 'Día del Niño', icon: '🎈', desc: 'El jugador con menor patrimonio cobra ₲ 200.000.', instant: true },
  { id: 'ruta_cortada', name: 'Ruta cortada', icon: '🚧', desc: 'Esta vuelta se mueve con un solo dado.', instant: false },
  { id: 'amnistia', name: 'Amnistía', icon: '🕊️', desc: 'Todos los presos salen de Tacumbú gratis.', instant: true },
  { id: 'sequia', name: 'Sequía', icon: '🌵', desc: 'Los solares sin casas no cobran alquiler esta vuelta.', instant: false },
  { id: 'san_juan', name: 'Fiesta de San Juan', icon: '🔥', desc: 'Pasar por Salida paga el doble durante esta vuelta.', instant: false },
  { id: 'mudanza', name: 'Mudanza', icon: '🚚', desc: 'Dos jugadores al azar intercambian su posición en el tablero.', instant: true },
  { id: 'solidaria', name: 'Cooperativa solidaria', icon: '🤲', desc: 'El de mayor efectivo le da ₲ 100.000 al de menor.', instant: true },
  { id: 'corte_ruta', name: 'Corte de ruta', icon: '🛣️', desc: 'Los transportes cobran el triple durante esta vuelta.', instant: false },
  { id: 'remate', name: 'Remate del banco', icon: '🔨', desc: 'Se subasta una propiedad libre al azar, desde ₲ 10.000.', instant: true },
  { id: 'terremoto', name: 'Terremoto', icon: '🌋', desc: 'Cada jugador pierde una casa al azar (el banco la recompra a mitad de precio).', instant: true },
  { id: 'loteria', name: 'Lotería', icon: '🎟️', desc: 'Sale un número: quien saque esa suma en su tirada esta vuelta cobra ₲ 300.000.', instant: false },
  { id: 'noche_casino', name: 'Noche de casino', icon: '🎰', desc: 'La ruleta paga doble y la apuesta máxima se duplica esta vuelta.', instant: false },
  { id: 'presidente', name: 'Visita del presidente', icon: '🎩', desc: 'Nadie paga alquiler en el Palacio de López esta vuelta, y quien caiga ahí cobra ₲ 100.000.', instant: false },
];

export interface MissionDef { id: string; text: string; reward: number; check: string }
/** Catálogo de misiones secretas. `check` es el nombre del contador/condición que evalúa el motor. */
export const MISSIONS: MissionDef[] = [
  { id: 'grupo', text: 'Completá un grupo de color', reward: 250, check: 'fullGroup' },
  { id: 'tres_alq', text: 'Cobrá 3 alquileres en una misma vuelta', reward: 200, check: 'rentsThisLap>=3' },
  { id: 'cinco_alq', text: 'Cobrá 5 alquileres en la partida', reward: 150, check: 'rentsCollected>=5' },
  { id: 'subasta_barata', text: 'Ganá una subasta por menos de ₲ 100.000', reward: 150, check: 'cheapAuctionWins>=1' },
  { id: 'subastas', text: 'Ganá 2 subastas', reward: 200, check: 'auctionsWon>=2' },
  { id: 'trivia', text: 'Ganá un desafío de trivia', reward: 200, check: 'triviaWins>=1' },
  { id: 'desafios', text: 'Ganá 2 desafíos', reward: 250, check: 'challengesWon>=2' },
  { id: 'casino', text: 'Ganá una apuesta en el Casino', reward: 150, check: 'casinoWins>=1' },
  { id: 'casas', text: 'Construí 4 casas', reward: 200, check: 'housesBuilt>=4' },
  { id: 'hotel', text: 'Construí un hotel', reward: 300, check: 'hotelsBuilt>=1' },
  { id: 'trade', text: 'Cerrá un intercambio con otro jugador', reward: 150, check: 'trades>=1' },
  { id: 'trades2', text: 'Cerrá 2 intercambios', reward: 250, check: 'trades>=2' },
  { id: 'preso', text: 'Caé preso en Tacumbú (y salí)', reward: 100, check: 'jailVisits>=1' },
  { id: 'efectivo', text: 'Tené ₲ 2.500.000 en efectivo', reward: 200, check: 'cash>=2500' },
  { id: 'patrimonio', text: 'Alcanzá un patrimonio de ₲ 3.000.000', reward: 250, check: 'netWorth>=3000' },
  { id: 'vueltas', text: 'Completá 4 vueltas al tablero', reward: 150, check: 'laps>=4' },
  { id: 'dobles', text: 'Sacá dobles 3 veces', reward: 150, check: 'doubles>=3' },
  { id: 'transportes', text: 'Tené 3 transportes', reward: 250, check: 'transports>=3' },
  { id: 'servicios', text: 'Tené ANDE y ESSAP', reward: 200, check: 'utilities>=2' },
  { id: 'ocho_prop', text: 'Tené 8 propiedades', reward: 250, check: 'properties>=8' },
  { id: 'hipoteca', text: 'Deshipotecá una propiedad', reward: 100, check: 'mortgagesRedeemed>=1' },
  { id: 'arena', text: 'Ganá una Arena', reward: 200, check: 'arenaWins>=1' },
  { id: 'don', text: 'Ganá un doble o nada de alquiler', reward: 150, check: 'donWins>=1' },
  { id: 'duelo', text: 'Ganá un Duelo mayor', reward: 300, check: 'duelsWon>=1' },
  { id: 'jackpot', text: 'Llevate el Jackpot', reward: 300, check: 'jackpots>=1' },
  { id: 'azul', text: 'Comprá una propiedad azul', reward: 150, check: 'ownsGroupAny:azul' },
  { id: 'marron', text: 'Tené las dos propiedades marrones', reward: 150, check: 'fullGroup:marron' },
  { id: 'palacio', text: 'Sé dueño del Palacio de López', reward: 200, check: 'owns:43' },
  { id: 'costanera', text: 'Sé dueño de la Costanera', reward: 200, check: 'owns:41' },
  { id: 'salidas', text: 'Pasá por Salida 3 veces', reward: 100, check: 'salaries>=3' },
];

/** Premios de la caja sorpresa de Salida. Promedio ≈ ₲ 200.000. */
export const LOOTBOX: { id: string; label: string; amount: number; weight: number }[] = [
  { id: 'g100', label: '₲ 100.000', amount: 100, weight: 16 },
  { id: 'g150', label: '₲ 150.000', amount: 150, weight: 20 },
  { id: 'g200', label: '₲ 200.000', amount: 200, weight: 22 },
  { id: 'g250', label: '₲ 250.000', amount: 250, weight: 15 },
  { id: 'g300', label: '₲ 300.000', amount: 300, weight: 10 },
  { id: 'g500', label: '₲ 500.000', amount: 500, weight: 5 },
  { id: 'casa', label: '¡Casa gratis!', amount: 0, weight: 4 },
  { id: 'carcel', label: 'Carta: Salís de Tacumbú', amount: 0, weight: 3 },
  { id: 'tirada', label: '¡Tirada extra!', amount: 0, weight: 3 },
  { id: 'multa', label: 'Multa de tránsito: −₲ 50.000', amount: -50, weight: 2 },
];

// ---------------------------------------------------------------------------
// Cartas contra el Paraguay (estilo "cartas contra la humanidad", humor local)
// ---------------------------------------------------------------------------
export const BLACK_CARDS: string[] = [
  'Lo que más se extraña del Paraguay de antes es ____.',
  'La verdadera causa de los cortes de la ANDE es ____.',
  'En la fiesta de 15 de mi prima no faltó ____.',
  'El nuevo sabor de chipa que nadie pidió: ____.',
  'Mi abuela cura todo con ____.',
  'Lo que encontraron en la terminal de Asunción a las 3 de la mañana: ____.',
  'El próximo ministro va a ser ____.',
  'La SET ahora también te cobra impuesto por ____.',
  'El Pombero se lleva a los que ____.',
  'Nada dice "domingo en familia" como ____.',
  'La excusa de mi jefe para no pagar el aguinaldo: ____.',
  'En el tereré de la oficina alguien puso ____.',
  'El tráfico en Asunción se arregla con ____.',
  'El último invento paraguayo: ____.',
  'Se cayó Internet en todo el país por culpa de ____.',
  'Mi tío en el asado siempre habla de ____.',
  'En Ciudad del Este te venden hasta ____.',
  'Cerro y Olimpia por fin se pusieron de acuerdo en ____.',
  'La nueva canción de la polca se llama "____".',
  'Lo que realmente hay dentro de la sopa paraguaya de la cantina: ____.',
  'El secreto para aprobar en la UNA: ____.',
  'A 45 grados en enero, lo único que ayuda es ____.',
  'El horóscopo dice que hoy te espera ____.',
  'El plan de gobierno tiene un solo punto: ____.',
  'Mi vecino arregló el auto con ____.',
  'Se casó por amor... y por ____.',
  'En el colectivo de la línea 30 vi ____.',
  'Lo que de verdad pasa en el Congreso a la noche: ____.',
  'La chipa se acompaña mejor con ____.',
  'Me quedé sin plata en Ñandepoly por ____.',
  'En el Mercado 4 conseguís ____ por 5 mil.',
  'El nuevo destino turístico del Paraguay: ____.',
  'Nunca invites al asado a alguien que trae ____.',
  'Mi mamá dice que me voy a enfermar por ____.',
  'La bandera del Paraguay debería tener también ____.',
  'El verdadero rey del carnaval de Encarnación es ____.',
  'Mi contraseña del banco es ____.',
  'Lo peor que le podés decir a un paraguayo: ____.',
  'El clásico regalo de Navidad que nadie quiere: ____.',
  'Después de tres tereré, empecé a ver ____.',
];

export const WHITE_CARDS: string[] = [
  'el Pombero con la tarjeta de crédito de mi papá', 'una chipa de la terminal de hace tres días', 'el tío que se hace el dormido cuando llega la cuenta',
  'la bombilla tapada', 'un corte de luz programado que nadie programó', 'el karaoke de la vecina a las 2 a.m.', 'la sopa paraguaya sin queso',
  'un pasaje de la línea 30 en hora pico', 'el gordo del asado que no come sino que opina', 'tereré con jugo de sobre', 'un político prometiendo una ruta',
  'el pan de la despensa de la esquina', 'la ex que volvió con un "hola, cómo andás"', 'un gato que se llama Tereré', 'mbeju recalentado en el microondas',
  'el que dice "yo ya sabía" después de todo', 'la señora que cobra el pasaje en moneditas', 'una moto con cinco personas', 'la cola del IPS a las 5 de la mañana',
  'el jugador que siempre sale bueno en el Palacio de López', 'el cuñado que vende celulares por WhatsApp', 'un jaguareté con sueño', 'el aire acondicionado en 16 grados',
  'la yerba con menta y mburucuyá', 'mandioca frita a las 4 de la tarde', 'una carreta con parlantes', 'el señor que reza en el colectivo', 'la playa de Encarnación llena de porteños',
  'una selfie con el Panteón de los Héroes', 'la abuela que dice "comé un poco más"', 'un chipero en bicicleta bajo la lluvia', 'el DJ del casamiento que puso cachaca tres horas',
  'una procesión a Caacupé en chancletas', 'la tía que pregunta cuándo te vas a casar', 'la remera de la Albirroja del 2010', 'un partido de Copa Libertadores a las 9 de la noche',
  'un ñandutí gigante para tapar el sol', 'el que paga la cuenta con billete de 100 mil', 'una moto sin espejo', 'el sonido de la bocina del panadero', 'el chico que vende chipa por la ventana',
  'un cortocircuito en la cocina de la tía', 'la vuelta manzana con la novia a los 15', 'el Impuesto al lujo', 'una casa gratis en Ñandepoly', 'el jackpot del casino',
  'la carta "Salís de Tacumbú"', 'el vecino que corta el pasto a las 7 a.m. del domingo', 'una empanada de mandioca más grande que la cabeza', 'el gol de Cabañas en 2010',
  'un asado sin sal', 'el lagarto del patio', 'la lista de precios del cine', 'un kilo de yerba a precio de oro', 'una fila para pagar la ANDE',
  'el primo que estudia hace 12 años', 'la moto de reparto que nunca llega', 'una polca a todo volumen en el bus', 'el olor a lluvia sobre el asfalto', 'un mango caído en el techo del auto',
  'la señora del kiosco que fía hasta fin de mes', 'el agua del tereré de otro', 'la Costanera un domingo a las 6 de la tarde', 'un cocido con leche quemado', 'el guardia del shopping',
  'la novela de las 9 de la noche', 'un mate lavado', 'el tío que llegó del Brasil con acento', 'una casa con techo de chapa a las 2 de la tarde',
  'la promesa de arreglar la calle antes de las elecciones', 'un chancho con celular', 'la trampa del casino', 'el sereno que se durmió', 'un bot que gana siempre',
  'la mano de truco con tres cuatros', 'el envido que no querían', 'un dibujante que dibuja círculos', 'el que grita "¡ARENA!" en la fiesta', 'una caja sorpresa con multa',
  'el Palacio de López inflable', 'el sapo del jardín de la abuela', 'el ventilador que hace ruido', 'una bolsa de hielo derretida', 'la chancleta voladora de mamá',
  'el mensaje "estoy llegando" a media hora', 'el que llega al asado con dos gaseosas y come por diez', 'una cooperativa que presta a nadie', 'un remate del banco a medianoche',
  'el karaoke con Los Nocheros', 'una cuenta de luz de 900 mil', 'el kuruguy que se metió en la casa', 'la balanza del mercado que "está bien"', 'un vendedor de perfumes en el semáforo',
  'el terreno del abuelo en Villa Hayes', 'el clásico que terminó 0 a 0', 'una foto borrosa del Luisón', 'el amigo que promete devolver la plata "la semana que viene"',
  'un tereré a las 6 de la mañana', 'la piscina de lona del vecino', 'un examen final un sábado', 'la chipa so\'o que se acabó antes de que llegues',
  'un abanico de cartón en misa', 'la clase de guaraní del colegio', 'el peluquero que corta lo que quiere', 'un fin de semana largo en San Bernardino',
  'el paraguayo que dice "ya está" y falta la mitad', 'la modista que no terminó el vestido', 'un ladrón de bombillas', 'el que se sirve el último pedazo sin preguntar',
];

// ---------------------------------------------------------------------------
// La foto borrosa: se va destapando un emoji; el primero que adivina gana la ronda
// ---------------------------------------------------------------------------
export const BLURRY: { emoji: string; answer: string; options: string[] }[] = [
  { emoji: '🧉', answer: 'Mate', options: ['Mate', 'Vaso de tereré', 'Cocido', 'Café'] },
  { emoji: '🐆', answer: 'Jaguareté', options: ['Jaguareté', 'Puma', 'Gato', 'Tigre de Bengala'] },
  { emoji: '🎼', answer: 'Partitura', options: ['Partitura', 'Arpa', 'Guitarra', 'Bandoneón'] },
  { emoji: '🚌', answer: 'Colectivo', options: ['Colectivo', 'Camión', 'Tren', 'Tractor'] },
  { emoji: '🥯', answer: 'Chipa', options: ['Chipa', 'Rosquilla', 'Dona', 'Bagel'] },
  { emoji: '🐊', answer: 'Yacaré', options: ['Yacaré', 'Lagarto', 'Iguana', 'Dinosaurio'] },
  { emoji: '⚽', answer: 'Pelota de fútbol', options: ['Pelota de fútbol', 'Pelota de básquet', 'Pelota de vóley', 'Sandía'] },
  { emoji: '🌽', answer: 'Choclo', options: ['Choclo', 'Banana', 'Zanahoria', 'Pepino'] },
  { emoji: '🏛️', answer: 'Palacio', options: ['Palacio', 'Iglesia', 'Estadio', 'Escuela'] },
  { emoji: '🎻', answer: 'Violín', options: ['Violín', 'Guitarra', 'Arpa', 'Cello'] },
  { emoji: '🛺', answer: 'Carreta motorizada', options: ['Carreta motorizada', 'Moto', 'Auto', 'Bicicleta'] },
  { emoji: '🍉', answer: 'Sandía', options: ['Sandía', 'Melón', 'Pelota', 'Tomate'] },
  { emoji: '🐸', answer: 'Sapo', options: ['Sapo', 'Tortuga', 'Lagartija', 'Cocodrilo'] },
  { emoji: '🌶️', answer: 'Locote picante', options: ['Locote picante', 'Zanahoria', 'Banana', 'Chorizo'] },
  { emoji: '🎸', answer: 'Guitarra', options: ['Guitarra', 'Violín', 'Arpa', 'Raqueta'] },
  { emoji: '🏍️', answer: 'Moto', options: ['Moto', 'Bicicleta', 'Auto', 'Carreta'] },
  { emoji: '🧀', answer: 'Queso', options: ['Queso', 'Pan', 'Manteca', 'Chipa'] },
  { emoji: '🐄', answer: 'Vaca', options: ['Vaca', 'Caballo', 'Perro', 'Chancho'] },
  { emoji: '🌴', answer: 'Palmera', options: ['Palmera', 'Pino', 'Cactus', 'Lapacho'] },
  { emoji: '🪗', answer: 'Acordeón', options: ['Acordeón', 'Piano', 'Arpa', 'Radio'] },
  { emoji: '🎂', answer: 'Torta de cumpleaños', options: ['Torta de cumpleaños', 'Sopa paraguaya', 'Pan', 'Helado'] },
  { emoji: '🚔', answer: 'Patrullero', options: ['Patrullero', 'Taxi', 'Ambulancia', 'Colectivo'] },
  { emoji: '🦜', answer: 'Loro', options: ['Loro', 'Gallina', 'Pato', 'Tucán'] },
  { emoji: '🥩', answer: 'Carne para el asado', options: ['Carne para el asado', 'Pescado', 'Pizza', 'Torta'] },
  { emoji: '🛶', answer: 'Canoa', options: ['Canoa', 'Barco', 'Avión', 'Carreta'] },
  { emoji: '⛪', answer: 'Iglesia', options: ['Iglesia', 'Palacio', 'Estadio', 'Hospital'] },
  { emoji: '🐍', answer: 'Víbora', options: ['Víbora', 'Lombriz', 'Manguera', 'Cinta'] },
  { emoji: '🌧️', answer: 'Lluvia', options: ['Lluvia', 'Sol', 'Nieve', 'Viento'] },
  { emoji: '🍌', answer: 'Banana', options: ['Banana', 'Luna', 'Choclo', 'Zapallo'] },
  { emoji: '🏟️', answer: 'Estadio', options: ['Estadio', 'Palacio', 'Iglesia', 'Piscina'] },
  { emoji: '🎣', answer: 'Caña de pescar', options: ['Caña de pescar', 'Escoba', 'Espada', 'Lápiz'] },
  { emoji: '🐴', answer: 'Caballo', options: ['Caballo', 'Vaca', 'Burro', 'Perro'] },
  { emoji: '🧅', answer: 'Cebolla', options: ['Cebolla', 'Ajo', 'Papa', 'Manzana'] },
  { emoji: '🎤', answer: 'Micrófono', options: ['Micrófono', 'Helado', 'Linterna', 'Martillo'] },
  { emoji: '🕸️', answer: 'Telaraña (ñandutí)', options: ['Telaraña (ñandutí)', 'Red de pesca', 'Rueda', 'Estrella'] },
  { emoji: '🍯', answer: 'Miel', options: ['Miel', 'Dulce de leche', 'Aceite', 'Yerba'] },
  { emoji: '🌵', answer: 'Cactus', options: ['Cactus', 'Palmera', 'Pino', 'Mandioca'] },
  { emoji: '🎈', answer: 'Globo', options: ['Globo', 'Pelota', 'Manzana', 'Foco'] },
  { emoji: '⛵', answer: 'Velero', options: ['Velero', 'Avión', 'Carpa', 'Sombrero'] },
  { emoji: '🍕', answer: 'Pizza', options: ['Pizza', 'Sopa paraguaya', 'Torta', 'Chipa guasu'] },
];

// ---------------------------------------------------------------------------
// Ordená la cadena: cuatro cosas para ordenar con un criterio; puntos por posiciones correctas
// ---------------------------------------------------------------------------
export const CHAINS: { title: string; items: string[] }[] = [
  { title: 'Ciudades de oeste a este', items: ['Asunción', 'Coronel Oviedo', 'Caaguazú', 'Ciudad del Este'] },
  { title: 'De norte a sur', items: ['Pedro Juan Caballero', 'Concepción', 'Asunción', 'Encarnación'] },
  { title: 'Hechos históricos, del más antiguo al más reciente', items: ['Fundación de Asunción', 'Independencia', 'Guerra del Chaco', 'Constitución de 1992'] },
  { title: 'Propiedades de Ñandepoly, de la más barata a la más cara', items: ['Villa Hayes', 'Luque', 'Villa Morra', 'Palacio de López'] },
  { title: 'Del más chico al más grande (en habitantes)', items: ['Pilar', 'Encarnación', 'Ciudad del Este', 'Asunción'] },
  { title: 'Meses del año, de primero a último', items: ['Marzo', 'Junio', 'Setiembre', 'Diciembre'] },
  { title: 'Del más barato al más caro (en general)', items: ['Una chipa', 'Un kilo de yerba', 'Un pasaje a Encarnación', 'Una moto'] },
  { title: 'Ríos, del más corto al más largo', items: ['Río Tebicuary', 'Río Pilcomayo', 'Río Paraguay', 'Río Paraná'] },
  { title: 'Del más frío al más caluroso', items: ['Julio', 'Mayo', 'Octubre', 'Enero'] },
  { title: 'Etapas de la vida, en orden', items: ['Bebé', 'Colegio', 'Universidad', 'Jubilación'] },
  { title: 'Cómo se hace el tereré, en orden', items: ['Poner la yerba', 'Poner la bombilla', 'Cargar el agua con hielo', 'Tomar'] },
  { title: 'Cómo se hace un asado, en orden', items: ['Prender el fuego', 'Salar la carne', 'Poner en la parrilla', 'Servir'] },
  { title: 'Del más lento al más rápido', items: ['Carreta', 'Bicicleta', 'Moto', 'Avión'] },
  { title: 'Grupos de Ñandepoly, del más barato al más caro', items: ['Marrón', 'Naranja', 'Verde', 'Azul'] },
  { title: 'Alquileres del transporte, de 1 a 4 transportes', items: ['₲ 25.000', '₲ 50.000', '₲ 100.000', '₲ 200.000'] },
  { title: 'Del más liviano al más pesado', items: ['Una chipa', 'Una sandía', 'Una bolsa de yerba de 25 kg', 'Una vaca'] },
  { title: 'Copas Libertadores de Olimpia, en orden', items: ['1979', '1990', '2002', '(la próxima)'] },
  { title: 'Del más corto al más largo (en tiempo)', items: ['Un partido de fútbol', 'Un viaje Asunción–CDE', 'Una Semana Santa', 'Un mandato presidencial'] },
  { title: 'Cadena alimenticia, del que come al que es comido', items: ['Jaguareté', 'Carpincho', 'Pasto', 'Tierra'] },
  { title: 'Fases de una partida de Ñandepoly, en orden', items: ['Crear la sala', 'Tirar los dados', 'Comprar propiedades', 'Cobrar alquileres'] },
  { title: 'Números romanos, de menor a mayor', items: ['IV', 'IX', 'XL', 'XC'] },
  { title: 'Del más cercano al más lejano de Asunción', items: ['Luque', 'Caacupé', 'Villarrica', 'Encarnación'] },
  { title: 'Monedas, de menor a mayor valor', items: ['₲ 100', '₲ 500', '₲ 1.000', '₲ 5.000'] },
  { title: 'Del amanecer a la noche', items: ['Desayuno', 'Almuerzo', 'Merienda', 'Cena'] },
  { title: 'Etapas de la chipa', items: ['Amasar', 'Hornear', 'Vender en la terminal', 'Comer'] },
];
