import type { TriviaQuestion } from './types';

// Banco de preguntas sobre Paraguay. `answer` es el índice (0-3) de la opción correcta.
const q = (qq: string, options: [string, string, string, string], answer: number): TriviaQuestion => ({ q: qq, options, answer });

export const TRIVIA: TriviaQuestion[] = [
  // Geografía
  q('¿Cuál es la capital de Paraguay?', ['Ciudad del Este', 'Asunción', 'Encarnación', 'Luque'], 1),
  q('¿Cuántos departamentos tiene Paraguay?', ['14', '17', '19', '23'], 1),
  q('¿Qué río separa a Paraguay de Argentina por el sur?', ['Río Pilcomayo', 'Río Paraguay', 'Río Paraná', 'Río Tebicuary'], 2),
  q('¿Qué río divide al país en región Oriental y Occidental?', ['Río Paraná', 'Río Paraguay', 'Río Apa', 'Río Ypané'], 1),
  q('¿Cómo se llama la región Occidental de Paraguay?', ['El Chaco', 'La Pampa', 'El Litoral', 'Misiones'], 0),
  q('¿Con qué país NO tiene frontera Paraguay?', ['Brasil', 'Bolivia', 'Uruguay', 'Argentina'], 2),
  q('¿Cuál es la capital del departamento de Alto Paraná?', ['Hernandarias', 'Presidente Franco', 'Ciudad del Este', 'Minga Guazú'], 2),
  q('¿Cuál es la capital del departamento de Itapúa?', ['Encarnación', 'Hohenau', 'Coronel Bogado', 'San Pedro del Paraná'], 0),
  q('¿Cuál es la capital del departamento Central?', ['Luque', 'San Lorenzo', 'Areguá', 'Capiatá'], 2),
  q('¿Cuál es la capital del departamento de Boquerón?', ['Filadelfia', 'Loma Plata', 'Mariscal Estigarribia', 'Neuland'], 0),
  q('¿Cuál es la capital del departamento de Cordillera?', ['Caacupé', 'Piribebuy', 'Tobatí', 'Altos'], 0),
  q('¿Cuál es la capital del departamento de Guairá?', ['Villarrica', 'Independencia', 'Mbocayaty', 'Yataity'], 0),
  q('¿Cuál es la capital del departamento de Caaguazú?', ['Caaguazú', 'Coronel Oviedo', 'Dr. J. Eulogio Estigarribia', 'Repatriación'], 1),
  q('¿Cuál es la capital del departamento de Amambay?', ['Bella Vista Norte', 'Capitán Bado', 'Pedro Juan Caballero', 'Zanja Pytã'], 2),
  q('¿Cuál es la capital del departamento de Ñeembucú?', ['Pilar', 'Alberdi', 'Humaitá', 'Cerrito'], 0),
  q('¿Cuál es la capital del departamento de Misiones?', ['San Ignacio', 'San Juan Bautista', 'Santa Rosa', 'Ayolas'], 1),
  q('¿Cuál es la capital del departamento de Paraguarí?', ['Carapeguá', 'Yaguarón', 'Paraguarí', 'Quiindy'], 2),
  q('¿Cuál es la capital del departamento de San Pedro?', ['San Estanislao', 'San Pedro de Ycuamandiyú', 'Santa Rosa del Aguaray', 'Choré'], 1),
  q('¿Cuál es la capital del departamento de Concepción?', ['Horqueta', 'Concepción', 'Belén', 'Loreto'], 1),
  q('¿Cuál es la capital del departamento de Canindeyú?', ['Curuguaty', 'Salto del Guairá', 'Katueté', 'Ypejhú'], 1),
  q('¿Cuál es la capital del departamento de Presidente Hayes?', ['Benjamín Aceval', 'Villa Hayes', 'Nanawa', 'Pozo Colorado'], 1),
  q('¿Cuál es la capital del departamento de Alto Paraguay?', ['Fuerte Olimpo', 'Bahía Negra', 'Puerto Casado', 'Carmelo Peralta'], 0),
  q('¿Cuál es la capital del departamento de Caazapá?', ['Yuty', 'San Juan Nepomuceno', 'Caazapá', 'Abaí'], 2),
  q('¿Cuál es el punto más alto de Paraguay?', ['Cerro Tres Kandú', 'Cerro Corá', 'Cerro Lambaré', 'Cerro Ybytyruzú'], 0),
  q('¿En qué departamento está el Cerro Tres Kandú?', ['Guairá', 'Paraguarí', 'Cordillera', 'Amambay'], 0),
  q('¿Qué lago está junto a San Bernardino y Areguá?', ['Lago Ypoá', 'Lago Ypacaraí', 'Lago Vera', 'Laguna Blanca'], 1),
  q('¿Qué represa comparte Paraguay con Brasil?', ['Yacyretá', 'Acaray', 'Itaipú', 'Corpus'], 2),
  q('¿Qué represa comparte Paraguay con Argentina?', ['Itaipú', 'Yacyretá', 'Yguazú', 'Acaray'], 1),
  q('¿Qué puente une Ciudad del Este con Foz de Iguazú?', ['Puente Remanso', 'Puente San Roque González', 'Puente de la Amistad', 'Puente Nanawa'], 2),
  q('¿Qué puente une Encarnación con Posadas?', ['Puente de la Amistad', 'Puente San Roque González de Santa Cruz', 'Puente Héroes del Chaco', 'Puente Remanso'], 1),
  q('¿Qué ciudad es conocida como la "Capital de la Fe"?', ['Caacupé', 'Itauguá', 'Yaguarón', 'Tobatí'], 0),
  q('¿Qué ciudad es famosa por el ñandutí?', ['Areguá', 'Itauguá', 'Luque', 'Piribebuy'], 1),
  q('¿Qué ciudad es conocida por su cerámica y sus frutillas?', ['Areguá', 'Atyrá', 'Tobatí', 'Ypacaraí'], 0),
  q('¿Qué ciudad es famosa por la filigrana de oro y plata y las arpas?', ['Luque', 'Limpio', 'Capiatá', 'Itá'], 0),
  q('¿Dónde está el Aeropuerto Internacional Silvio Pettirossi?', ['Asunción', 'Luque', 'Mariano Roque Alonso', 'San Lorenzo'], 1),
  q('¿Cuál es el segundo aeropuerto internacional del país?', ['Guaraní (Minga Guazú)', 'Encarnación', 'Concepción', 'Mariscal Estigarribia'], 0),
  q('¿Qué río forma la frontera norte con Brasil en Concepción?', ['Río Apa', 'Río Ypané', 'Río Aquidabán', 'Río Jejuí'], 0),
  q('¿Cuál es la ciudad más poblada del país después de Asunción?', ['Luque', 'San Lorenzo', 'Ciudad del Este', 'Capiatá'], 2),
  q('¿En qué departamento están las ruinas jesuíticas de Trinidad y Jesús?', ['Misiones', 'Itapúa', 'Paraguarí', 'Guairá'], 1),
  q('¿Qué comunidad menonita está en el Chaco Central?', ['Filadelfia', 'Nueva Germania', 'Colonia Independencia', 'Hohenau'], 0),
  q('¿Cómo se llama el gran humedal del sur de Ñeembucú?', ['Esteros del Ñeembucú', 'Pantanal', 'Ypoá', 'Estero Patiño'], 0),
  q('¿Qué cataratas están cerca de Ciudad del Este, del lado argentino y brasileño?', ['Saltos del Monday', 'Cataratas del Iguazú', 'Salto Cristal', 'Saltos del Guairá'], 1),
  q('¿Qué salto de agua está en Presidente Franco, Alto Paraná?', ['Salto Cristal', 'Saltos del Monday', 'Salto Suizo', 'Salto Ñacunday'], 1),

  // Historia
  q('¿En qué año se independizó Paraguay?', ['1810', '1811', '1816', '1821'], 1),
  q('¿En qué mes se celebra la Independencia paraguaya?', ['Marzo', 'Mayo', 'Agosto', 'Septiembre'], 1),
  q('¿Qué día se celebra la Independencia?', ['14 y 15 de mayo', '25 de mayo', '12 de junio', '15 de agosto'], 0),
  q('¿Quién fue el primer presidente constitucional de Paraguay?', ['Francisco Solano López', 'Carlos Antonio López', 'José Gaspar Rodríguez de Francia', 'Fulgencio Yegros'], 1),
  q('¿Cómo se lo conocía a José Gaspar Rodríguez de Francia?', ['El Mariscal', 'El Supremo', 'El Karaí Guasu', 'El Libertador'], 1),
  q('¿En qué años se libró la Guerra del Chaco?', ['1865-1870', '1904-1908', '1932-1935', '1947'], 2),
  q('¿Contra qué país fue la Guerra del Chaco?', ['Argentina', 'Brasil', 'Bolivia', 'Uruguay'], 2),
  q('¿En qué años fue la Guerra contra la Triple Alianza?', ['1811-1813', '1864-1870', '1932-1935', '1870-1876'], 1),
  q('¿Qué países formaron la Triple Alianza?', ['Argentina, Brasil y Uruguay', 'Argentina, Bolivia y Chile', 'Brasil, Bolivia y Perú', 'Argentina, Brasil y Chile'], 0),
  q('¿Dónde murió el Mariscal Francisco Solano López?', ['Humaitá', 'Piribebuy', 'Cerro Corá', 'Curupayty'], 2),
  q('¿En qué fecha murió el Mariscal López?', ['1 de marzo de 1870', '15 de mayo de 1811', '12 de junio de 1935', '25 de diciembre de 1868'], 0),
  q('¿Qué batalla infantil se recuerda cada 16 de agosto (Día del Niño)?', ['Batalla de Acosta Ñu', 'Batalla de Curupayty', 'Batalla de Boquerón', 'Batalla de Tuyutí'], 0),
  q('¿Qué se conmemora el 12 de junio?', ['Día de la Paz del Chaco', 'Día de la Independencia', 'Día de la Bandera', 'Día del Idioma Guaraní'], 0),
  q('¿Qué se celebra el 14 de agosto?', ['Día del Folklore', 'Día de la Bandera', 'Fundación de Asunción', 'Día del Maestro'], 1),
  q('¿En qué año fue fundada Asunción?', ['1524', '1537', '1541', '1580'], 1),
  q('¿Quién fundó Asunción?', ['Juan de Salazar y Espinosa', 'Domingo Martínez de Irala', 'Pedro de Mendoza', 'Álvar Núñez Cabeza de Vaca'], 0),
  q('¿Qué héroe de la Guerra del Chaco da nombre a una ciudad del Chaco?', ['Mariscal Estigarribia', 'General Díaz', 'Coronel Oviedo', 'Capitán Bado'], 0),
  q('¿Quién fue el comandante paraguayo en la Guerra del Chaco?', ['Bernardino Caballero', 'José Félix Estigarribia', 'Eusebio Ayala', 'Rafael Franco'], 1),
  q('¿En qué año cayó la dictadura de Alfredo Stroessner?', ['1954', '1979', '1989', '1992'], 2),
  q('¿Cuántos años duró el gobierno de Stroessner?', ['15', '24', '35', '42'], 2),
  q('¿En qué año se promulgó la Constitución vigente de Paraguay?', ['1967', '1989', '1992', '2000'], 2),
  q('¿Qué presidente fue conocido como "El Mariscal"?', ['Carlos Antonio López', 'Francisco Solano López', 'Bernardino Caballero', 'Eusebio Ayala'], 1),
  q('¿Quién fue la heroína que lideró a las mujeres en Piribebuy y Areguá durante la Guerra Grande?', ['Juana de Lara', 'Serafina Dávalos', 'Las Residentas', 'Elisa Lynch'], 2),
  q('¿Cómo se llamaba la compañera irlandesa del Mariscal López?', ['Elisa Lynch', 'Juana Pesoa', 'Pancha Garmendia', 'Madame Lynch Pessoa'], 0),
  q('¿Qué fortaleza fue clave en la Guerra Grande, a orillas del río Paraguay?', ['Humaitá', 'Curupayty', 'Itapirú', 'Boquerón'], 0),
  q('¿En qué batalla de 1866 Paraguay obtuvo una gran victoria defensiva?', ['Tuyutí', 'Curupayty', 'Acosta Ñu', 'Piribebuy'], 1),
  q('¿Qué fortín fue escenario de la primera gran batalla de la Guerra del Chaco?', ['Nanawa', 'Boquerón', 'Toledo', 'Picuiba'], 1),

  // Símbolos, idioma y cultura
  q('¿Cuáles son los idiomas oficiales de Paraguay?', ['Español y portugués', 'Español y guaraní', 'Guaraní y jopará', 'Español, guaraní e inglés'], 1),
  q('¿Qué significa "ñande" en guaraní?', ['Ellos', 'Vos', 'Nosotros (incluyendo al que escucha)', 'Yo'], 2),
  q('¿Qué significa "mba\'éichapa"?', ['Gracias', '¿Cómo estás?', 'Buenos días', 'Adiós'], 1),
  q('¿Qué significa "aguyje"?', ['Perdón', 'Gracias', 'Hola', 'Por favor'], 1),
  q('¿Qué significa "jaha"?', ['Comamos', 'Vamos', 'Vení', 'Dormí'], 1),
  q('¿Qué significa "che"?', ['Yo / mi', 'Vos', 'Ellos', 'Amigo'], 0),
  q('¿Qué significa "kuñataĩ"?', ['Señora', 'Niño', 'Señorita / muchacha', 'Abuela'], 2),
  q('¿Qué significa "karai"?', ['Señor', 'Niño', 'Perro', 'Casa'], 0),
  q('¿Qué significa "mitã"?', ['Casa', 'Niño', 'Agua', 'Comida'], 1),
  q('¿Qué significa "y" en guaraní?', ['Fuego', 'Tierra', 'Agua', 'Sol'], 2),
  q('¿Qué significa "pytã"?', ['Rojo', 'Azul', 'Verde', 'Blanco'], 0),
  q('¿Qué significa "hovy"?', ['Rojo', 'Azul o verde', 'Amarillo', 'Negro'], 1),
  q('¿Qué significa "morotĩ"?', ['Negro', 'Blanco', 'Rojo', 'Gris'], 1),
  q('¿Qué significa "sa\'yju"?', ['Amarillo', 'Verde', 'Marrón', 'Rosa'], 0),
  q('¿Qué significa "ka\'aguy"?', ['Río', 'Bosque / monte', 'Cerro', 'Camino'], 1),
  q('¿Qué significa "óga"?', ['Perro', 'Casa', 'Puerta', 'Ciudad'], 1),
  q('¿Qué significa "jagua"?', ['Gato', 'Perro', 'Tigre', 'Caballo'], 1),
  q('¿Qué significa "mbarakaja"?', ['Perro', 'Gato', 'Pájaro', 'Vaca'], 1),
  q('¿Qué significa "kavaju"?', ['Vaca', 'Caballo', 'Cabra', 'Cerdo'], 1),
  q('¿Qué es el "jopará"?', ['Un baile', 'La mezcla de guaraní y español', 'Una comida', 'Un instrumento'], 1),
  q('¿Qué planta es la base del mate y el tereré?', ['Coca', 'Yerba mate', 'Menta', 'Cedrón'], 1),
  q('¿Qué es el tereré?', ['Yerba mate con agua caliente', 'Yerba mate con agua fría', 'Un dulce', 'Un baile'], 1),
  q('¿Cómo se llaman las hierbas medicinales que se agregan al tereré?', ['Remedios yuyos', 'Chipas', 'Poha ñana', 'Ka\'a he\'ẽ'], 2),
  q('¿Cuál es la planta paraguaya famosa como endulzante natural?', ['Ka\'a he\'ẽ (stevia)', 'Cedrón', 'Menta\'i', 'Burrito'], 0),
  q('¿Qué comida tradicional se hace con almidón, queso y huevo y se come en Semana Santa?', ['Sopa paraguaya', 'Chipa', 'Mbeju', 'Vori vori'], 1),
  q('¿Cómo se llama la sopa paraguaya?', ['Un caldo de pollo', 'Una torta salada de maíz y queso', 'Una sopa de verduras', 'Un guiso de carne'], 1),
  q('¿Qué es el "vori vori"?', ['Un postre', 'Un caldo con bolitas de maíz y queso', 'Un pan', 'Una bebida'], 1),
  q('¿Qué es el "mbeju"?', ['Una torta de almidón y queso a la sartén', 'Un jugo', 'Un pescado', 'Una fruta'], 0),
  q('¿Qué es la "chipa guasu"?', ['Chipa chiquita', 'Torta de choclo (maíz tierno) y queso', 'Pan dulce', 'Chipa de Semana Santa'], 1),
  q('¿Qué es el "kivevé"?', ['Sopa de zapallo y harina de maíz', 'Un asado', 'Una ensalada', 'Un pescado frito'], 0),
  q('¿Qué es el "mbaipy"?', ['Polenta de maíz con queso', 'Un baile', 'Un instrumento', 'Un pájaro'], 0),
  q('¿Qué es la "sopa so\'o"?', ['Sopa paraguaya con carne', 'Caldo de pescado', 'Postre de leche', 'Guiso de arroz'], 0),
  q('¿Qué bebida alcohólica tradicional se hace de caña de azúcar?', ['Cocido', 'Caña paraguaya', 'Clericó', 'Mosto'], 1),
  q('¿Qué es el "cocido"?', ['Un guiso', 'Yerba mate quemada con azúcar, con agua caliente y leche', 'Un pan', 'Un pescado'], 1),
  q('¿Qué es el "clericó"?', ['Un vino con frutas típico de Navidad', 'Una sopa', 'Un pan', 'Un dulce'], 0),
  q('¿Qué instrumento es símbolo de la música paraguaya?', ['Guitarra', 'Arpa paraguaya', 'Bandoneón', 'Acordeón'], 1),
  q('¿Qué ritmo musical es típico de Paraguay?', ['Cumbia villera', 'Polca paraguaya', 'Samba', 'Chamamé'], 1),
  q('¿Qué género musical lento y romántico nació en Paraguay?', ['Tango', 'Guarania', 'Bolero', 'Vals'], 1),
  q('¿Quién creó la guarania?', ['Agustín Barrios', 'José Asunción Flores', 'Emiliano R. Fernández', 'Félix Pérez Cardozo'], 1),
  q('¿Qué guitarrista paraguayo es mundialmente famoso, apodado "Mangoré"?', ['Agustín Barrios', 'Luis Alberto del Paraná', 'Berta Rojas', 'Félix Pérez Cardozo'], 0),
  q('¿Qué canción es considerada el himno popular de la Guerra del Chaco, de Emiliano R. Fernández?', ['13 Tuyutí', 'Recuerdos de Ypacaraí', 'India', 'Che la reina'], 0),
  q('¿Quién compuso la música de "Recuerdos de Ypacaraí"?', ['Demetrio Ortiz', 'José Asunción Flores', 'Agustín Barrios', 'Luis Alberto del Paraná'], 0),
  q('¿Qué baile paraguayo se hace con botellas sobre la cabeza?', ['Danza de la galopera', 'Danza de la botella', 'Polca kyre\'ỹ', 'Chopi'], 1),
  q('¿Qué encaje tradicional imita la tela de araña?', ['Ao po\'i', 'Ñandutí', 'Encaje ju', 'Poyvi'], 1),
  q('¿Qué tela bordada típica se hace en Yataity?', ['Ñandutí', 'Ao po\'i', 'Poyvi', 'Karanda\'y'], 1),
  q('¿Cuántas estrellas tiene el escudo de la bandera paraguaya?', ['Ninguna', 'Una', 'Dos', 'Tres'], 1),
  q('¿Qué tiene de particular la bandera paraguaya?', ['Tiene cuatro colores', 'Es la única con un escudo distinto en cada cara', 'Es cuadrada', 'No tiene escudo'], 1),
  q('¿Qué frase aparece en el reverso de la bandera?', ['Paz y Justicia', 'Libertad o Muerte', 'Unión y Fuerza', 'Dios, Patria y Libertad'], 0),
  q('¿Cuál es la flor nacional de Paraguay?', ['Lapacho', 'Mburucuyá (pasionaria)', 'Jazmín', 'Orquídea'], 1),
  q('¿Cuál es el árbol nacional de Paraguay?', ['Lapacho', 'Ceibo', 'Quebracho', 'Yvyra pytã'], 0),
  q('¿Cuál es el ave nacional de Paraguay?', ['Tucán', 'Pájaro campana', 'Ñandú', 'Guyra pytã'], 1),
  q('¿Cómo se llama la moneda de Paraguay?', ['Peso', 'Real', 'Guaraní', 'Sol'], 2),
  q('¿Qué figura mitológica guaraní es el protector de los animales y el monte, y silba de noche?', ['Jasy Jateré', 'Pombero', 'Kurupi', 'Luisón'], 1),
  q('¿Qué personaje mitológico es un niño rubio que se lleva a los chicos en la siesta?', ['Jasy Jateré', 'Pombero', 'Moñái', 'Teju Jagua'], 0),
  q('¿Qué personaje mitológico es el séptimo hijo varón, convertido en perro?', ['Kurupi', 'Luisón', 'Ao Ao', 'Mbói Tu\'ĩ'], 1),
  q('¿Cuántos hijos tuvieron Tau y Kerana según la mitología guaraní?', ['Cinco', 'Seis', 'Siete', 'Nueve'], 2),
  q('¿Qué es la "Semana Santa" en Paraguay famosa por comer?', ['Asado', 'Chipa', 'Pizza', 'Empanadas'], 1),
  q('¿Qué se celebra el 8 de diciembre en Caacupé?', ['La Virgen de Caacupé', 'La Independencia', 'San Blas', 'La Fundación'], 0),
  q('¿Quién es el santo patrono de Paraguay?', ['San Blas', 'San Roque', 'San Juan', 'San Francisco'], 0),
  q('¿Qué fiesta popular de junio incluye el "tata ári jehasa" (caminar sobre brasas)?', ['San Blas', 'San Juan', 'Semana Santa', 'Año Nuevo'], 1),
  q('¿Qué juego de la fiesta de San Juan consiste en trepar un palo enjabonado?', ['Yvyra syĩ', 'Toro candil', 'Pelota tata', 'Kambuchi jejoka'], 0),
  q('¿Qué escritor paraguayo escribió "Yo el Supremo"?', ['Augusto Roa Bastos', 'Gabriel Casaccia', 'Josefina Plá', 'Rafael Barrett'], 0),
  q('¿Qué premio ganó Augusto Roa Bastos en 1989?', ['Nobel', 'Cervantes', 'Príncipe de Asturias', 'Planeta'], 1),
  q('¿Cuál es el nombre del estadio de fútbol más grande de Paraguay?', ['La Olla', 'Defensores del Chaco', 'Manuel Ferreira', 'Feliciano Cáceres'], 1),
  q('¿Qué club paraguayo ganó la Copa Libertadores tres veces?', ['Cerro Porteño', 'Libertad', 'Olimpia', 'Guaraní'], 2),
  q('¿En qué año Olimpia ganó su primera Copa Libertadores?', ['1972', '1979', '1990', '2002'], 1),
  q('¿Cómo se llama el clásico del fútbol paraguayo?', ['Olimpia vs Cerro Porteño', 'Libertad vs Guaraní', 'Olimpia vs Libertad', 'Cerro vs Nacional'], 0),
  q('¿Qué arquero paraguayo fue famoso por meter goles de tiro libre?', ['Justo Villar', 'José Luis Chilavert', 'Roberto Fernández', 'Antony Silva'], 1),
  q('¿En qué ciudad tiene sede la CONMEBOL?', ['Asunción', 'Luque', 'Buenos Aires', 'Río de Janeiro'], 1),
  q('¿A qué instancia llegó Paraguay en el Mundial 2010, su mejor resultado?', ['Octavos', 'Cuartos de final', 'Semifinal', 'Final'], 1),
  q('¿Qué paraguayo ganó la medalla de plata en fútbol en los Juegos Olímpicos de Atenas 2004?', ['La selección paraguaya', 'Olimpia', 'Cerro Porteño', 'Libertad'], 0),
  q('¿Qué deporte practica el paraguayo Fabrizio Zanotti?', ['Tenis', 'Golf', 'Natación', 'Atletismo'], 1),
  q('¿Qué tenista paraguayo llegó al top 10 mundial en los años 80?', ['Ramón Delgado', 'Víctor Pecci', 'Rossana de los Ríos', 'Francisco González'], 1),
  q('¿Qué colectivo de transporte público es típico de Asunción?', ['El metro', 'El colectivo (bus)', 'El tranvía', 'El tren'], 1),
  q('¿Cómo se llama la costanera de Asunción sobre el río Paraguay?', ['Costanera José Asunción Flores', 'Costanera Sur', 'Avenida Mariscal López', 'Malecón'], 0),
  q('¿Qué barrio popular de Asunción está junto a la bahía, también llamado Ricardo Brugada?', ['Chacarita', 'Villa Morra', 'Sajonia', 'Recoleta'], 0),
  q('¿Qué edificio es la sede del Poder Ejecutivo paraguayo?', ['Palacio de Justicia', 'Palacio de los López', 'Cabildo', 'Panteón de los Héroes'], 1),
  q('¿Qué monumento de Asunción guarda los restos de los héroes nacionales?', ['Cabildo', 'Panteón Nacional de los Héroes', 'Catedral', 'Palacio de López'], 1),
  q('¿Cuántos senadores tiene el Congreso paraguayo?', ['30', '45', '60', '80'], 1),
  q('¿Cuántos diputados tiene la Cámara de Diputados?', ['45', '60', '80', '100'], 2),
  q('¿Cuánto dura el mandato presidencial en Paraguay?', ['4 años', '5 años', '6 años', '8 años'], 1),
  q('¿Cuál es el código telefónico internacional de Paraguay?', ['+54', '+55', '+591', '+595'], 3),
  q('¿Cuál es el dominio de internet de Paraguay?', ['.pa', '.py', '.pr', '.pg'], 1),
  q('¿Qué empresa estatal provee la energía eléctrica en Paraguay?', ['ESSAP', 'ANDE', 'COPACO', 'PETROPAR'], 1),
  q('¿Qué empresa estatal provee el agua potable en Asunción?', ['ANDE', 'COPACO', 'ESSAP', 'INC'], 2),
  q('¿Qué producto agrícola es la principal exportación de Paraguay?', ['Algodón', 'Soja', 'Caña de azúcar', 'Mandioca'], 1),
  q('¿De qué es Paraguay uno de los mayores exportadores mundiales, junto con la soja?', ['Carne bovina', 'Café', 'Cacao', 'Vino'], 0),
  q('¿Qué energía exporta Paraguay en grandes cantidades?', ['Petróleo', 'Gas', 'Electricidad', 'Carbón'], 2),
  q('¿Qué tubérculo acompaña casi todas las comidas paraguayas?', ['Papa', 'Batata', 'Mandioca', 'Zanahoria'], 2),
  q('¿Qué fruta da nombre a la ciudad de Mbocayaty?', ['Mango', 'Mbokaja (coco paraguayo)', 'Guayaba', 'Aguacate'], 1),
  q('¿Qué animal es el "jaguareté"?', ['Puma', 'Jaguar / yaguareté', 'Ocelote', 'Zorro'], 1),
  q('¿Qué animal es el "karumbe"?', ['Tortuga', 'Rana', 'Lagarto', 'Pez'], 0),
  q('¿Qué animal es el "mborevi"?', ['Tapir', 'Ciervo', 'Carpincho', 'Oso hormiguero'], 0),
  q('¿Qué animal es el "kapi\'yva" (carpincho)?', ['El roedor más grande del mundo', 'Un ave', 'Un pez de río', 'Un felino'], 0),
  q('¿Qué pez es típico del río Paraguay y se come frito o en chupín?', ['Salmón', 'Surubí', 'Trucha', 'Atún'], 1),
  q('¿Qué pez de los ríos paraguayos es famoso por su fuerza al pescarlo?', ['Dorado', 'Bagre', 'Mojarra', 'Anguila'], 0),
  q('¿Qué ciudad celebra un famoso carnaval con desfiles y "espuma"?', ['Villarrica', 'Encarnación', 'Pilar', 'Caacupé'], 1),
  q('¿Cómo se llama la fiesta con carreras de caballos y sortija típica del interior?', ['Jineteada', 'Carrera de sortija', 'Rodeo', 'Kambuchi'], 1),
  q('¿Qué ciudad es conocida como la "Perla del Sur"?', ['Pilar', 'Encarnación', 'Ayolas', 'San Ignacio'], 1),
  q('¿Qué ciudad junto al lago Ypacaraí es conocida como la "Capital del Verano"?', ['Areguá', 'San Bernardino', 'Ypacaraí', 'Itauguá'], 1),
  q('¿Qué ciudad de Cordillera es conocida por la "chipa Barrero"?', ['Eusebio Ayala (Barrero Grande)', 'Caacupé', 'Itacurubí', 'Altos'], 0),
  q('¿Qué personaje de las fiestas de San Juan es un muñeco de trapo que se quema?', ['Judas kái', 'Pombero', 'Kurupi', 'Toro candil'], 0),

  // --- Ampliación v1.3.5 ---
  q('¿Cuál es el departamento más poblado de Paraguay?', ['Central', 'Alto Paraná', 'Itapúa', 'Caaguazú'], 0),
  q('¿En qué departamento está Ciudad del Este?', ['Canindeyú', 'Alto Paraná', 'Caaguazú', 'Itapúa'], 1),
  q('¿Cuál es la capital del departamento de Itapúa?', ['Pilar', 'Encarnación', 'Villarrica', 'Coronel Oviedo'], 1),
  q('¿Cuál es la capital del departamento de Guairá?', ['Villarrica', 'Paraguarí', 'Caazapá', 'Ybycuí'], 0),
  q('¿Cuál es la capital del departamento de Ñeembucú?', ['Pilar', 'Ayolas', 'San Juan Bautista', 'Humaitá'], 0),
  q('¿Con qué países limita Paraguay?', ['Brasil, Argentina y Bolivia', 'Brasil, Uruguay y Bolivia', 'Argentina, Chile y Bolivia', 'Brasil, Argentina y Perú'], 0),
  q('¿Cuál de estas ciudades está sobre el río Paraná?', ['Concepción', 'Encarnación', 'Caacupé', 'Villarrica'], 1),
  q('¿Qué ciudad es conocida como la "Capital del Sol"?', ['San Bernardino', 'Encarnación', 'Pilar', 'Areguá'], 1),
  q('¿Qué ciudad es famosa por sus frutillas y su cerámica?', ['Areguá', 'Itauguá', 'Luque', 'Yaguarón'], 0),
  q('¿Qué ciudad es la cuna del ñandutí?', ['Itauguá', 'Areguá', 'Capiatá', 'Ypacaraí'], 0),
  q('¿En qué ciudad se fabrican tradicionalmente las joyas de filigrana?', ['Luque', 'San Lorenzo', 'Limpio', 'Ñemby'], 0),
  q('¿Qué lago está entre San Bernardino y Areguá?', ['Lago Ypacaraí', 'Lago Ypoá', 'Lago Yguazú', 'Laguna Blanca'], 0),
  q('¿Cómo se llama el salto de agua más famoso de Paraguarí?', ['Salto Cristal', 'Salto Suizo', 'Salto Ñacunday', 'Salto Monday'], 1),
  q('¿Dónde está el Salto Monday?', ['Presidente Franco', 'Encarnación', 'Villarrica', 'Concepción'], 0),
  q('¿Qué parque nacional está en el Chaco, cerca de la frontera con Bolivia?', ['Defensores del Chaco', 'Ybycuí', 'Cerro Corá', 'San Rafael'], 0),
  q('¿En qué parque nacional murió el Mariscal López?', ['Cerro Corá', 'Ybycuí', 'Ñacunday', 'Caaguazú'], 0),
  q('¿Cuál es la principal exportación agrícola de Paraguay?', ['Soja', 'Café', 'Banana', 'Arroz'], 0),
  q('¿Qué animal ganadero hizo famoso al Chaco paraguayo?', ['Vacuno', 'Ovino', 'Porcino', 'Equino'], 0),
  q('¿Con qué país comparte Paraguay la represa de Yacyretá?', ['Argentina', 'Brasil', 'Bolivia', 'Uruguay'], 0),
  q('¿Con qué país comparte Paraguay la represa de Itaipú?', ['Brasil', 'Argentina', 'Bolivia', 'Uruguay'], 0),
  q('¿Cómo se llama el aeropuerto internacional de Ciudad del Este?', ['Guaraní', 'Silvio Pettirossi', 'Ñu Guasú', 'Carlos A. López'], 0),
  q('¿Qué significa "Paraguay" según una de las versiones más aceptadas?', ['Agua de los payaguá', 'Tierra sin mal', 'Río de las palmas', 'Lugar del sol'], 0),
  q('¿En qué año se firmó el Tratado de Asunción que creó el Mercosur?', ['1985', '1991', '1995', '2001'], 1),
  q('¿Qué ciudad paraguaya es sede de la Secretaría del Mercosur?', ['Asunción', 'Luque', 'Ciudad del Este', 'Encarnación'], 1),
  q('¿Qué organismo del fútbol sudamericano tiene su sede en Luque?', ['CONMEBOL', 'FIFA', 'UEFA', 'CONCACAF'], 0),
  q('¿Cuántas estrellas tiene el escudo nacional del Paraguay?', ['Una', 'Tres', 'Cinco', 'Ninguna'], 0),
  q('¿Qué tiene de particular la bandera paraguaya?', ['Tiene emblemas distintos en cada cara', 'Es cuadrada', 'No tiene colores', 'Tiene siete franjas'], 0),
  q('¿Qué flor es la flor nacional del Paraguay?', ['Mburucuyá', 'Rosa', 'Orquídea', 'Jazmín'], 0),
  q('¿Cuál es el árbol nacional del Paraguay?', ['Lapacho', 'Timbó', 'Quebracho', 'Yvyra pytã'], 0),
  q('¿Cuál es el ave nacional del Paraguay?', ['Pájaro campana (guyra campana)', 'Tucán', 'Cardenal', 'Colibrí'], 0),
  q('¿Qué animal aparece en el billete de mayor denominación en circulación?', ['Un jaguareté', 'Un caballo', 'Una vaca', 'Un carpincho'], 0),
  q('¿Qué es el "karumbe" en guaraní?', ['Tortuga', 'Conejo', 'Zorro', 'Lagarto'], 0),
  q('¿Qué significa "jagua" en guaraní?', ['Perro', 'Gato', 'Vaca', 'Caballo'], 0),
  q('¿Qué significa "kuarahy" en guaraní?', ['Sol', 'Luna', 'Estrella', 'Lluvia'], 0),
  q('¿Qué significa "y" en guaraní?', ['Agua', 'Fuego', 'Tierra', 'Aire'], 0),
  q('¿Qué significa "che" en guaraní?', ['Yo / mi', 'Vos', 'Él', 'Nosotros'], 0),
  q('¿Cómo se dice "gracias" en guaraní?', ['Aguyje', 'Mba´éichapa', 'Jajotopata', 'Iporã'], 0),
  q('¿Qué quiere decir "mba´éichapa"?', ['¿Cómo estás?', 'Hasta luego', 'Buen provecho', 'Por favor'], 0),
  q('¿Qué significa "iporã"?', ['Está bien / lindo', 'Está feo', 'Tengo hambre', 'Vamos'], 0),
  q('¿Qué comida paraguaya se hace con maíz, queso y leche y no es una sopa?', ['Sopa paraguaya', 'Mbejú', 'Chipa guasú', 'Vori vori'], 0),
  q('¿Cuál de estos platos lleva bolitas de maíz en caldo?', ['Vori vori', 'Mbejú', 'Chipa so´o', 'Payaguá mascada'], 0),
  q('¿Qué es la "payaguá mascada"?', ['Torta de mandioca y carne', 'Un postre de miel', 'Una bebida', 'Un pan dulce'], 0),
  q('¿Qué lleva la chipa so´o que no lleva la chipa común?', ['Carne', 'Chocolate', 'Dulce de leche', 'Banana'], 0),
  q('¿Con qué se hace tradicionalmente el mbejú?', ['Almidón de mandioca', 'Harina de trigo', 'Arroz', 'Avena'], 0),
  q('¿Qué bebida caliente se toma con leche en las mañanas frías?', ['Cocido', 'Tereré', 'Mosto', 'Clericó'], 0),
  q('¿Qué es el "mosto" en Paraguay?', ['Jugo de caña de azúcar', 'Vino joven', 'Cerveza artesanal', 'Licor de miel'], 0),
  q('¿Qué bebida se prepara con vino y frutas en las fiestas?', ['Clericó', 'Caña', 'Mosto', 'Cocido'], 0),
  q('¿Qué hierba se usa para "refrescar" el tereré?', ['Menta´i', 'Canela', 'Clavo de olor', 'Romero'], 0),
  q('¿Cómo se llama el recipiente donde se toma el tereré?', ['Guampa', 'Mate', 'Termo', 'Bombilla'], 0),
  q('¿Qué día se celebra el Día Nacional del Tereré?', ['Último sábado de febrero', '14 de mayo', '15 de agosto', '1 de marzo'], 0),
  q('¿Qué se celebra el 14 y 15 de mayo?', ['La Independencia', 'La Paz del Chaco', 'La fundación de Asunción', 'El Día del Niño'], 0),
  q('¿Qué se recuerda el 1 de marzo?', ['Día de los Héroes', 'La Independencia', 'La Paz del Chaco', 'El Día de la Juventud'], 0),
  q('¿Qué se conmemora el 12 de junio?', ['Paz del Chaco', 'Independencia', 'Día de la Raza', 'Fundación de Asunción'], 0),
  q('¿Qué se recuerda el 16 de agosto?', ['Día del Niño', 'Día de la Madre', 'Día del Padre', 'Día del Maestro'], 0),
  q('¿Qué se celebra el 8 de diciembre en Caacupé?', ['Día de la Virgen', 'Navidad', 'Año Nuevo', 'Día de la Independencia'], 0),
  q('¿Cómo se llama la Virgen de Caacupé?', ['Virgen de los Milagros', 'Virgen del Rosario', 'Virgen de Fátima', 'Virgen del Carmen'], 0),
  q('¿Qué instrumento acompaña siempre a la polca paraguaya?', ['Arpa', 'Piano', 'Saxofón', 'Batería'], 0),
  q('¿Quién compuso "Recuerdos de Ypacaraí"?', ['Demetrio Ortiz', 'José Asunción Flores', 'Agustín Barrios', 'Herminio Giménez'], 0),
  q('¿Quién creó la guarania?', ['José Asunción Flores', 'Demetrio Ortiz', 'Emiliano R. Fernández', 'Félix Pérez Cardozo'], 0),
  q('¿Qué guitarrista paraguayo es famoso mundialmente por "La Catedral"?', ['Agustín Barrios Mangoré', 'Berta Rojas', 'Luis Alberto del Paraná', 'Óscar Nelson Safuán'], 0),
  q('¿Qué guitarrista paraguaya fue nominada al Grammy?', ['Berta Rojas', 'Lizza Bogado', 'Ana Barreto', 'Maneco Galeano'], 0),
  q('¿Cómo se llama la danza tradicional donde se baila con botellas en la cabeza?', ['Danza de la botella', 'Chopi', 'Golondrina', 'Palomita'], 0),
  q('¿Qué escritor paraguayo escribió "Yo el Supremo"?', ['Augusto Roa Bastos', 'Gabriel Casaccia', 'Josefina Plá', 'Rafael Barrett'], 0),
  q('¿Qué premio internacional ganó Augusto Roa Bastos en 1989?', ['Premio Cervantes', 'Premio Nobel', 'Premio Planeta', 'Premio Rómulo Gallegos'], 0),
  q('¿Qué película paraguaya ganó premios en el Festival de Berlín en 2018?', ['Las herederas', 'Hamaca paraguaya', '7 cajas', 'Latas vacías'], 0),
  q('¿De qué trata la película "7 cajas"?', ['Un carretillero en el Mercado 4', 'Un viaje al Chaco', 'La Guerra Grande', 'Un equipo de fútbol'], 0),
  q('¿Qué club paraguayo ganó tres veces la Copa Libertadores?', ['Olimpia', 'Cerro Porteño', 'Libertad', 'Guaraní'], 0),
  q('¿En qué año Olimpia ganó la Copa Intercontinental?', ['1979', '1990', '2002', '1985'], 0),
  q('¿Cómo se llama el estadio de Cerro Porteño?', ['La Nueva Olla', 'Defensores del Chaco', 'Manuel Ferreira', 'La Huerta'], 0),
  q('¿Cómo se llama el estadio de Olimpia?', ['Manuel Ferreira', 'La Nueva Olla', 'Defensores del Chaco', 'Feliciano Cáceres'], 0),
  q('¿Cuál es el estadio más grande del Paraguay?', ['Defensores del Chaco', 'La Nueva Olla', 'Manuel Ferreira', 'Antonio Aranda'], 1),
  q('¿Qué arquero paraguayo jugó tres mundiales y también hacía goles?', ['José Luis Chilavert', 'Justo Villar', 'Roberto Fernández', 'Ever Almeida'], 0),
  q('¿Hasta qué instancia llegó Paraguay en el Mundial 2010?', ['Cuartos de final', 'Octavos', 'Semifinal', 'Fase de grupos'], 0),
  q('¿En qué año Paraguay llegó a la final de la Copa América por última vez?', ['2011', '2004', '1999', '2015'], 0),
  q('¿Qué deportista paraguaya ganó medalla olímpica en 2024?', ['Nadie ganó medalla individual antes de 2024', 'Una nadadora', 'Un boxeador', 'Un tirador'], 0),
  q('¿Qué selección paraguaya ganó la plata olímpica en Atenas 2004?', ['Fútbol masculino', 'Vóley', 'Handball', 'Básquet'], 0),
  q('¿Qué animal es el carpincho?', ['El roedor más grande del mundo', 'Un felino', 'Un ave', 'Un reptil'], 0),
  q('¿Qué animal paraguayo también se llama "oso hormiguero gigante"?', ['Jurumí', 'Tapir', 'Aguará guasú', 'Mborevi'], 0),
  q('¿Qué es el "aguará guasú"?', ['Un zorro de crin', 'Un oso', 'Un mono', 'Un pez'], 0),
  q('¿Cómo se llama el pez más buscado en el río Paraguay para pescar?', ['Dorado', 'Salmón', 'Trucha', 'Mero'], 0),
  q('¿Qué es el "surubí"?', ['Un pez de río', 'Un pájaro', 'Un árbol', 'Una serpiente'], 0),
  q('¿Qué reptil gigante vive en el Pantanal paraguayo?', ['Anaconda (curiyú)', 'Cocodrilo del Nilo', 'Iguana marina', 'Tortuga gigante'], 0),
  q('¿Qué insecto transmite el dengue?', ['Mosquito Aedes aegypti', 'Abeja', 'Hormiga', 'Mosca común'], 0),
  q('¿Qué se recomienda para evitar el dengue en casa?', ['Eliminar agua estancada', 'Regar más las plantas', 'Dejar baldes llenos', 'Abrir las ventanas'], 0),
  q('¿Qué mide el "IPS" en Paraguay?', ['Es el seguro social', 'Un impuesto', 'Un índice de precios', 'Una ruta'], 0),
  q('¿Qué hace la SET?', ['Cobra los impuestos', 'Genera electricidad', 'Controla el tránsito', 'Reparte agua'], 0),
  q('¿Qué empresa provee la electricidad en Paraguay?', ['ANDE', 'ESSAP', 'COPACO', 'PETROPAR'], 0),
  q('¿Qué empresa provee agua potable en Asunción?', ['ESSAP', 'ANDE', 'COPACO', 'DINAC'], 0),
  q('¿Qué ruta une Asunción con Ciudad del Este?', ['Ruta PY02', 'Ruta PY01', 'Ruta PY09', 'Ruta PY03'], 0),
  q('¿Qué ruta lleva de Asunción a Encarnación?', ['Ruta PY01', 'Ruta PY02', 'Ruta PY05', 'Ruta PY08'], 0),
  q('¿Cómo se llama la ruta que cruza el Chaco hacia Bolivia?', ['Ruta Transchaco (PY09)', 'Ruta PY02', 'Ruta PY06', 'Ruta PY04'], 0),
  q('¿Qué puente une Ciudad del Este con Foz de Iguazú?', ['Puente de la Amistad', 'Puente Remanso', 'Puente Héroes del Chaco', 'Puente San Roque'], 0),
  q('¿Qué puente une Encarnación con Posadas?', ['Puente San Roque González', 'Puente de la Amistad', 'Puente Remanso', 'Puente Nanawa'], 0),
  q('¿Cuál es la moneda de Paraguay?', ['Guaraní', 'Peso', 'Real', 'Boliviano'], 0),
  q('¿Qué prócer aparece en el billete de 50.000 guaraníes?', ['Agustín Barrios', 'Carlos A. López', 'José G. Rodríguez de Francia', 'Bernardino Caballero'], 0),
  q('¿Cuál fue el primer ferrocarril de Sudamérica junto con otros pocos?', ['El de Paraguay (1861)', 'El de Perú', 'El de Colombia', 'El de Bolivia'], 0),
  q('¿Qué presidente paraguayo gobernó de 1954 a 1989?', ['Alfredo Stroessner', 'Higinio Morínigo', 'Federico Chaves', 'Juan Natalicio González'], 0),
  q('¿Contra qué países luchó Paraguay en la Guerra Grande?', ['Brasil, Argentina y Uruguay', 'Bolivia y Perú', 'Chile y Argentina', 'Brasil y Bolivia'], 0),
  q('¿En qué años fue la Guerra del Chaco?', ['1932-1935', '1864-1870', '1947-1949', '1920-1923'], 0),
  q('¿Quién fue el primer dictador perpetuo del Paraguay?', ['Dr. José Gaspar Rodríguez de Francia', 'Carlos Antonio López', 'Francisco Solano López', 'Bernardino Caballero'], 0),
  q('¿Qué batalla de la Guerra del Chaco es la más recordada?', ['Boquerón', 'Curupayty', 'Tuyutí', 'Piribebuy'], 0),
  q('¿Qué ciudad fue capital provisoria durante la Guerra Grande?', ['Piribebuy', 'Villarrica', 'Concepción', 'Pilar'], 0),
];

export const TRIVIA_COUNT = TRIVIA.length;
