import { chromium } from 'playwright';
const BASE='http://localhost:8080';
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH });
const ctx = await browser.newContext({ viewport: { width: 1600, height: 900 } });
const ctx2 = await browser.newContext({ viewport: { width: 1600, height: 900 } });
const a = await ctx.newPage(), b = await ctx2.newPage();
await a.goto(BASE); await a.fill('input[placeholder="Ej: Ivan"]', 'Ivan'); await a.click('button:has-text("Crear sala")');
await a.waitForURL(/\/sala\//); const code = a.url().split('/sala/')[1];
await b.goto(`${BASE}/sala/${code}`); await b.waitForSelector('button:has-text("Entrar a la sala")');
await b.fill('input[maxlength="20"]', 'Lucía'); await b.click('button[title="Chipa"]'); await b.click('button:has-text("Entrar a la sala")');
await a.waitForSelector('text=Jugadores (2/6)'); await a.click('button:has-text("Empezar partida")'); await a.waitForSelector('.board');
await a.hover('[data-tile="7"]'); await a.waitForTimeout(500);
const bb = await a.locator('.board').boundingBox();
await a.screenshot({ path: 'e2e/casa/lupa-lateral.png', clip: { x: bb.x - 20, y: bb.y + bb.height*0.3, width: bb.width*0.5, height: bb.height*0.5 } });
await a.hover('[data-tile="38"]'); await a.waitForTimeout(500);
await a.screenshot({ path: 'e2e/casa/lupa-abajo.png', clip: { x: bb.x + bb.width*0.4, y: bb.y + bb.height*0.6, width: bb.width*0.6, height: bb.height*0.45 } });
await a.hover('[data-tile="0"]'); await a.waitForTimeout(500);
await a.screenshot({ path: 'e2e/casa/lupa-esquina.png', clip: { x: bb.x + bb.width*0.5, y: bb.y + bb.height*0.5, width: bb.width*0.55, height: bb.height*0.55 } });
await browser.close();
